version: '3.3'
services:
  node1:
    networks:
      - project-net
    # build: ./apps/nodes/
    image: buronf/nodes
    hostname: node1
    container_name: node1
    environment:
      - RELEASE_COOKIE=cookie
      - RELEASE_DISTRIBUTION=sname
      - RELEASE_NODE=node1@node1
  node2:
    networks:
      - project-net
    # build: ./apps/nodes/
    image: buronf/nodes
    hostname: node2
    container_name: node2
    environment:
      - RELEASE_COOKIE=cookie
      - RELEASE_DISTRIBUTION=sname
      - RELEASE_NODE=node2@node2
  node3:
    networks:
      - project-net
    # build: ./apps/nodes/
    image: buronf/nodes
    hostname: node3
    container_name: node3
    environment:
      - RELEASE_COOKIE=cookie
      - RELEASE_DISTRIBUTION=sname
      - RELEASE_NODE=node3@node3
      
  backend:
    tty: true
    depends_on:
      - node1
      - node2
      - node3
    networks:
      - project-net
    ports:
      - "8080:8080"
    # build: ./apps/backend/
    image: buronf/backend
    hostname: backend
    container_name: backend
    environment:
      - RELEASE_COOKIE=cookie
      - RELEASE_DISTRIBUTION=sname
      - RELEASE_NODE=backend@backend

  frontend:
    tty: true
    depends_on:
      - backend
    networks:
      - project-net
    ports:
      - "3000:3000"
    # build: ./apps/frontend/
    image: buronf/frontend
    hostname: frontend
    container_name: frontend
    environment:
      - RELEASE_COOKIE=cookie
      - RELEASE_DISTRIBUTION=sname
      - RELEASE_NODE=frontend@frontend


networks:
  project-net:
    driver: bridge